<!DOCTYPE html>
<!-- Header //-->
<html>

<head>
    <title>Error - Page Not Found | SBCert-POP Application</title>

    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta name="viewport" content="initial-scale=1.0">
</head>

<body>
<!-- Content //-->
<div id="content">
    <h1>Sorry, that page was not found.</h1>

    <p>Please use this links to test the application:</p>
    <ul>
        <li><a href="/admin">Admin</a></li>
        <li><a href="/register">Register</a></li>
    </ul>
</div>
</body>

</html>